### ISSUE TITLE
URLs recently became case sensitive

### ISSUE THREAD

**Issue by benbalter** [18F/18f.gsa.gov#1333] opened 2015-11-25 20:40 UTC
I have a link to https://18f.gsa.gov/2015/02/25/We-Are-Hiring/, which recently started 404ing. 

https://18f.gsa.gov/2015/02/25/we-are-hiring/ continues to work.

I suspect URLs *shouldn't* be case sensitive (although they can be), and that the change wasn't intentional.

**Comment by konklone** [comment] 2015-11-25 21:10
@benbalter and @parkr -- any reason why our recent upgrade to Jekyll 3 might have caused this behavior to change?

**Comment by parkr** [comment] 2015-11-25 21:12
@konklone Are you using 3.0.1?

**Comment by konklone** [comment] 2015-11-25 21:12
Yep, as of [2 days ago](https://github.com/18F/18f.gsa.gov/commit/f43217d0a0cdd2a081ba3406d57bd3a66f519c68).

**Comment by parkr** [comment] 2015-11-25 22:06
Hm, it seems these should remain cased if using `:title`, per https://github.com/jekyll/jekyll/blob/918bfd5fe5f9f411869f3bfbbf81a478316f04b2/lib/jekyll/document.rb#L189-L190. Fixed in https://github.com/jekyll/jekyll/pull/4100 and released in 3.0.1. Trying it on my local system allows both URLs, but that is probably more a feature of my being on a Mac and having this case insensitive file system.

I'll look into it.

**Comment by konklone** [comment] 2015-11-25 22:28
Hmm. From everything I've read so far, I don't know why we ever would have had a working URL that used improper title-case. We serve the content on a case-sensitive Linux file system, nginx doesn't add any opinions on case-sensitivity into the stack, and we've never disseminated title-case URLs to my memory.

@benbalter, are you **sure** the URL used to work that way? Can you find any examples of us sharing a title-case URL?

**Comment by benbalter** [comment] 2015-11-25 22:38
> @benbalter, are you sure the URL used to work that way? Can you find any examples of us sharing a title-case URL?

I have CI on my site, and the URL has been in [my 18F post](http://ben.balter.com/2015/04/22/the-difference-between-18f-and-usds/) since April, and not failing with the mixed case. A quick google search shows widespread reference to mixed-case URLs being shared (and not corrected):

* https://www.facebook.com/DCWebWomen/posts/997871470247547
* https://twitter.com/aaronsnow/status/570792144660783105
* https://github.com/18F/joining-18f/issues/64, https://github.com/18F/joining-18f/issues/62 (commit message)
* https://news.ycombinator.com/item?id=9231817 (@leahbannon's post)
* https://news.ycombinator.com/item?id=9233282 (@aaronsnow's post), and my personal favorite
* http://htmlmade.com/site/konklone.com

Oh, and also twice within this repo: https://github.com/18F/18f.gsa.gov/blob/aebe8f0082e89b1e3477171be515ec3626b3e676/_posts/2015-03-20-one-year-in-and-looking-forward.md and https://github.com/18F/18f.gsa.gov/blob/b56a7173d5dce16a1ccac40bfa48ff9e4957f83c/_posts/2015-05-21-TockingTime.md (dat [CI for your content](http://ben.balter.com/2015/05/22/test-your-prose/) :smile_cat: )

**Comment by konklone** [comment] 2015-11-25 22:59
Ah ha, now I understand. We do have a few posts who used title case in their file name, including two in February:

```
2015-02-25-We-Are-Hiring.md
2015-02-26-Five-Ways-To-Turn-A-Bad-Idea-Into-A-Great-One.md
```

So, those used to work, and the referenced Jekyll thread is what's causing us breakage. Jekyll is now downcasing slugs where it was not before, which breaks our links. Since Jekyll is a static site generator with necessarily close coupling to filesystem semantics, this seems like a risky move for Jekyll -- especially if the change was made in a patch version increase (`3.0.0` -> `3.0.1`).

**Comment by benbalter** [comment] 2015-11-25 23:19
As a stopgap, you could always use jekyll-redirect-from to preserve the old URLs, assuming those aren't downcased as well.

**Comment by rebornix** [comment] 2015-11-26 05:21
I'm the guy behind breaking Jekyll pr you mentioned. Sorry for any confusion it brought. But If I remember correctly, `title` in Jekyll 2.x is cased and 3.0.0 broke this behavior. So the history of post title is like

- 2.x: case sensitive
- 3.0.0.pre - 3.0.0: case not sensitive 
- 3.0.1: case sensitive

Currently GitHub Page is using Jekyll 2.x (not quite sure which minor version) and it's case sensitive (see [example](http://blog.three.sh/jekyll/update/2015/10/14/Welcome-To-Jekyll.html)).

I agree with @konklone , it's a risky move for a batch version for Jekyll but it's a necessary turnaround for most Jekyll users (including all GitHub Page users) **IMO**. Most posts are using lowercase slug so maybe that's why you guys didn't notice the change in URLs when upgrading to Jekyll 3.0.0.pre.

If you really like lowercase slug, another stopgap is setting your permalink as `/:year/:month/:day/:slug/`.

**Comment by konklone** [comment] 2015-11-26 05:58
@rebornix Hmm. We were using Jekyll 2.x in February, when we made and clearly distributed the title-cased links to the post @benbalter identified. (We didn't try out Jekyll 3 beta [until April](https://github.com/18F/18f.gsa.gov/commit/eefa05645f7cf2d4142893c38708e1c6d5ee71a2).)

The page filename has [stayed the same throughout](https://github.com/18F/18f.gsa.gov/commits/staging/_posts/2015-02-25-We-Are-Hiring.md), so it was the case that the URL of https://18f.gsa.gov/2015/02/25/We-Are-Hiring/ worked with the current filename under Jekyll 2.x.

I'm not sure what happened in `3.0.0` -- we've only used `3.0.0` for a short amount of time, so we wouldn't have noticed the regression if it existed -- but it looks like `3.0.1` is down-casing the generated file name to `we-are-hiring/index.html` where it did not in 2.x. That seems like a regression.

**Comment by rebornix** [comment] 2015-11-26 06:01
@konklone Avoid downcasing is what we all try to achieve, let me take a deep look into it.

**Comment by konklone** [comment] 2015-11-26 06:09
@rebornix Wait, no! You've described it perfectly.

It turns out we'd only deployed Jekyll 3.0.1 to staging, and not yet to production. And staging works just fine:

https://staging.18f.gov/2015/02/25/We-Are-Hiring/

So we'll fix this the next time we sync our `staging` branch to `production`.

Thank you for talking out the problem with me, @rebornix, and @benbalter for pointing out the issue.

**Comment by parkr** [comment] 2015-11-26 19:37
> staging works just fine

:smile: 

Thanks for jumping in, @rebornix!

**Closed** 2016-10-18 15:20 UTC
