### ISSUE TITLE
Code block formatting looks visually off -- visual/frontend bug

### ISSUE THREAD

**Issue by alexsobledotgov** [18F/18f.gsa.gov#4022] opened 2024-07-24 15:49 UTC
## Expected Behavior

Each numbered line in a code block should line up visually with the text.

## Actual Behavior

<img width="711" alt="Screenshot 2024-07-24 at 10 48 06 AM" src="https://github.com/user-attachments/assets/71f1e6a3-d632-4044-b9d7-1ecf6fe8e775">

https://18f.gsa.gov/2024/07/17/working-with-oracle-databases-in-open-source-projects/

**Comment by beechnut** [comment] 2024-07-24 17:49
I strongly suspect tis is directly caused by a CSS line I wrote, and I think when we merged other styles in it caused this bug. I'll revert that when I get a moment.

Thanks for catching this

**Comment by beechnut** [comment] 2024-07-25 02:16
@alexsobledotgov The preview build looks good to me — if it looks good to you, let me know and I'll merge.

**Closed** 2024-07-25 15:33 UTC
Labels: type:bug
