### ISSUE TITLE
Tests are failing in new version of ruby.

### ISSUE THREAD

**Issue by eddietejeda** [18F/18f.gsa.gov#2884] opened 2018-09-10 16:29 UTC
The tests are failing in the new version of Ruby.

/Users/eddie/.rvm/gems/ruby-2.5.1@18f.gsa.gov/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `load': cannot load such file -- /Users/eddie/Code/18f.gsa.gov/_layouts/spec/_plugins/author_data_spec.rb (LoadError)

It appears that paths are getting screwed up.

**Comment by lsgitter** [comment] 2019-07-02 16:45
@apburnes is this a duplicate of the ruby update task?

**Comment by apburnes** [comment] 2019-07-02 17:21
This will be closed by #2873

**Comment by lsgitter** [comment] 2019-07-09 22:43
#21873 was approved on 7/9/2019

**Closed** 2019-07-09 22:42 UTC
